/**
 * The site is generated from `data/links.json`, which is itself generated by
 * `scripts/sync-links.py` from the links data sheet. Nothing here should ever
 * reach out to that source directly — the committed JSON is the seam between
 * the two flows, so a build works offline and every data change lands as a
 * reviewable diff.
 */
export default function (eleventyConfig) {
  eleventyConfig.addPassthroughCopy("src/style.css");
  eleventyConfig.addPassthroughCopy("src/index.js");
  eleventyConfig.addPassthroughCopy("src/static");

  // Matches the favicon service the page used when it rendered client-side.
  eleventyConfig.addFilter("faviconUrl", function (url) {
    try {
      return "https://www.google.com/s2/favicons?sz=64&domain=" + new URL(url).hostname;
    } catch (e) {
      return "";
    }
  });

  // Section numbers are displayed as 01, 02, ...
  eleventyConfig.addFilter("sectionNumber", function (index) {
    return String(index).padStart(2, "0");
  });

  // `search` is optional in the data; fall back to the lowercased label.
  eleventyConfig.addFilter("searchTerms", function (item) {
    return item.search || (item.label || item.name || "").toLowerCase();
  });

  return {
    dir: {
      input: "src",
      output: "_site",
      includes: "_includes",
      data: "_data",
    },
  };
}
