#!/usr/bin/env python3
"""Create a Links CMS Airtable base for a new site and write its schema file.

Usage:
  init-base.py --workspace wspXXXXXXXX [--name "Links CMS"]
  init-base.py --base appXXXXXXXX          adopt an existing base instead
  init-base.py --workspace wsp... --dry-run

This is the missing half of forking the site. `data/airtable-schema.json` is a
map of table and field IDs, and those IDs are generated by Airtable — they
cannot be guessed, copied from upstream, or written by hand without an hour of
clicking through the API. So this builds the base from data/airtable-spec.json
and then writes the schema file from what Airtable actually returned.

Requires AIRTABLE_TOKEN with scopes:
  schema.bases:write   create the base, tables, and fields
  schema.bases:read    read back the IDs (implied by write, requested anyway)

Creating a base needs a workspace ID: open the workspace in Airtable and copy
the wsp... segment out of the URL.

Two phases, because a link field needs its target table to exist first:
  1. create the base with every table and its non-link fields
  2. add link fields, which makes Airtable create the symmetric field too
"""
import argparse
import json
import os
import sys
import urllib.error
import urllib.request

API_ROOT = "https://api.airtable.com/v0"
HERE = os.path.dirname(__file__)
SPEC_PATH = os.path.join(HERE, "..", "data", "airtable-spec.json")
SCHEMA_PATH = os.path.join(HERE, "..", "data", "airtable-schema.json")


def api(method, path, token, payload=None):
    url = f"{API_ROOT}/meta{path}"
    data = json.dumps(payload).encode() if payload is not None else None
    request = urllib.request.Request(url, data=data, method=method)
    request.add_header("Authorization", f"Bearer {token}")
    if data:
        request.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return json.load(response)
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", "replace")
        hint = ""
        if e.code == 403:
            hint = ("\nHint: the token needs the schema.bases:write scope AND the "
                    "workspace must be in the token's allowed bases/workspaces list.")
        raise SystemExit(f"Airtable returned {e.code} for {method} {path}: {body}{hint}")


def field_payload(field, spec, table_ids):
    """Translate one spec field into the Meta API's field object."""
    out = {"name": field["name"], "type": field["type"]}
    if field.get("description"):
        out["description"] = field["description"]

    if field["type"] == "number":
        # Orders are integers; without an explicit precision the API rejects it.
        out["options"] = {"precision": 0}
    elif field["type"] == "checkbox":
        out["options"] = {"color": "greenBright", "icon": "check"}
    elif field["type"] == "singleSelect":
        choices = spec[field["choicesFrom"]]
        out["options"] = {"choices": [{"name": c} for c in choices]}
    elif field["type"] == "link":
        out["type"] = "multipleRecordLinks"
        out["options"] = {
            "linkedTableId": table_ids[field["linkTo"]],
            # One section per item, one project per resource. The sync reads
            # only the first linked ID, so allowing many would silently drop
            # every link but one.
            "prefersSingleRecordLink": True,
        }
    return out


def build_schema(spec, base_id, base_name, tables_response):
    """Map the spec's stable keys onto the IDs Airtable handed back."""
    by_name = {t["name"]: t for t in tables_response}
    schema = {
        "_comment": [
            "GENERATED by scripts/init-base.py — do not hand-edit.",
            "Identifiers for this site's Airtable base. These are addresses, not",
            "secrets: the API token is the secret and lives in a GitHub Actions",
            "secret, never here. The sync reads this so tables and fields can be",
            "renamed in Airtable without breaking the build.",
        ],
        "baseId": base_id,
        "baseName": base_name,
        "tables": {},
        "statuses": spec["statuses"],
    }

    for table in spec["tables"]:
        live = by_name.get(table["name"])
        if live is None:
            raise SystemExit(f"table '{table['name']}' is missing from the base")
        live_fields = {f["name"]: f["id"] for f in live["fields"]}

        fields = {}
        for field in table["fields"]:
            field_id = live_fields.get(field["name"])
            if field_id is None:
                raise SystemExit(
                    f"field '{field['name']}' is missing from table '{table['name']}'"
                )
            fields[field["key"]] = field_id

        schema["tables"][table["key"]] = {"id": live["id"], "fields": fields}

    return schema


def create_base(spec, workspace_id, name, token):
    """Phase 1: base plus every table and its non-link fields."""
    tables = []
    for table in spec["tables"]:
        fields = [
            field_payload(f, spec, {})
            for f in table["fields"]
            if f["type"] != "link"
        ]
        # Airtable uses the first field as the primary; make sure that is the
        # one the spec marks, since the primary cannot be changed via the API.
        primary = next(f["name"] for f in table["fields"] if f.get("primary"))
        fields.sort(key=lambda f: f["name"] != primary)
        tables.append({
            "name": table["name"],
            "description": table.get("description", ""),
            "fields": fields,
        })

    created = api("POST", "/bases", token,
                  {"name": name, "workspaceId": workspace_id, "tables": tables})
    print(f"Created base {created['id']} ({name})")
    return created["id"]


def add_link_fields(spec, base_id, token):
    """Phase 2: link fields, now that every table exists."""
    live = api("GET", f"/bases/{base_id}/tables", token)["tables"]
    table_ids = {}
    for table in spec["tables"]:
        match = next((t for t in live if t["name"] == table["name"]), None)
        if match is None:
            raise SystemExit(f"table '{table['name']}' not found in base {base_id}")
        table_ids[table["key"]] = match["id"]

    existing = {t["name"]: {f["name"] for f in t["fields"]} for t in live}

    for table in spec["tables"]:
        for field in table["fields"]:
            if field["type"] != "link":
                continue
            if field["name"] in existing.get(table["name"], set()):
                print(f"  {table['name']}.{field['name']} already exists; left alone")
                continue
            api("POST", f"/bases/{base_id}/tables/{table_ids[table['key']]}/fields",
                token, field_payload(field, spec, table_ids))
            print(f"  {table['name']}.{field['name']} -> {field['linkTo']}")

    return table_ids


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--workspace", help="workspace ID (wsp...) to create the base in")
    parser.add_argument("--base", help="adopt an existing base (app...) instead of creating one")
    parser.add_argument("--name", default="Links CMS", help="name for the new base")
    parser.add_argument("--dry-run", action="store_true",
                        help="print the payloads without calling Airtable")
    args = parser.parse_args()

    with open(SPEC_PATH, encoding="utf-8") as f:
        spec = json.load(f)

    if args.dry_run:
        tables = []
        for table in spec["tables"]:
            fields = [field_payload(f, spec, {k["key"]: "tblDRYRUNDRYRUNxx" for k in spec["tables"]})
                      for f in table["fields"]]
            tables.append({"name": table["name"], "fields": fields})
        json.dump({"name": args.name, "tables": tables}, sys.stdout, indent=2)
        print()
        return

    if bool(args.workspace) == bool(args.base):
        raise SystemExit("pass exactly one of --workspace (create) or --base (adopt)")

    token = os.environ.get("AIRTABLE_TOKEN")
    if not token:
        raise SystemExit("AIRTABLE_TOKEN is not set")

    if args.base:
        base_id = args.base
        print(f"Adopting existing base {base_id}")
    else:
        base_id = create_base(spec, args.workspace, args.name, token)

    print("Adding link fields...")
    add_link_fields(spec, base_id, token)

    live = api("GET", f"/bases/{base_id}/tables", token)["tables"]
    schema = build_schema(spec, base_id, args.name, live)

    with open(SCHEMA_PATH, "w", encoding="utf-8") as f:
        json.dump(schema, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"\nWrote {os.path.normpath(SCHEMA_PATH)} for base {base_id}")
    print("Next: python3 scripts/doctor.py, then seed the base and run sync-links.py.")


if __name__ == "__main__":
    main()
