/**
 * Global data for the site, read from the committed `data/links.json`.
 *
 * That file is generated by `scripts/sync-links.py` and reviewed as a diff
 * before it lands, so the build reads it straight off disk rather than
 * fetching from the upstream source.
 */
import { readFile } from "node:fs/promises";

export default async function () {
  const url = new URL("../../data/links.json", import.meta.url);
  return JSON.parse(await readFile(url, "utf8"));
}
